PRG-4-PROJEK/Models/Mahasiswa.cs
using System;
using System.Data.SqlClient;
using System.Security.Cryptography;
using System.Text;

namespace PRG_4_PROJEK.Models
{
    public class Mahasiswa
    {
        private readonly string _connectionString;
        private readonly SqlConnection _connection;
            
        public Mahasiswa(IConfiguration configuration)
        {
            _connectionString = configuration.GetConnectionString("DefaultConnection");

            _connection = new SqlConnection(_connectionString);
        }

        public MahasiswaModel getDataByUsername(string rfid)
        {
            MahasiswaModel mahasiswaModel = new MahasiswaModel();
            try
            {
                string query = "SELECT * from mahasiswa where rfid = @p1";
                SqlCommand command = new SqlCommand(query, _connection);
                command.Parameters.AddWithValue("@p1", rfid);
                _connection.Open();
                SqlDataReader reader = command.ExecuteReader();

                if (reader.Read())
                {
                    mahasiswaModel.nim = reader["nim"].ToString();
                    mahasiswaModel.nama = reader["nama"].ToString();
                    mahasiswaModel.rfid = reader["rfid"].ToString();
                    mahasiswaModel.pin = reader["pin"].ToString();
                    mahasiswaModel.jk = reader["jenis_kelamin"].ToString();
                    mahasiswaModel.jp = Convert.ToInt32(reader["jam_plus"]);
                    mahasiswaModel.jm = Convert.ToInt32(reader["jam_minus"]);
                    mahasiswaModel.softskil = reader["softskil"].ToString();
                    mahasiswaModel.status = reader["status"].ToString();
                }
                else
                {
                    return null;
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                throw;
            }
            finally 
            {
                _connection.Close();
            }
            return mahasiswaModel;
        }
        public MahasiswaModel getDataByPassword(string rfid, string pin)
        {

            MahasiswaModel mahasiswaModel = new MahasiswaModel();
            try
            {
                string encryptedPIN = EncryptPIN(pin);
                string query = "SELECT * FROM mahasiswa WHERE pin = @p1 and rfid = @p2";
                SqlCommand command = new SqlCommand(query, _connection);
                command.Parameters.AddWithValue("@p1", encryptedPIN);
                command.Parameters.AddWithValue("@p2", rfid);
                _connection.Open();
                SqlDataReader reader = command.ExecuteReader();

                if (reader.Read())
                {
                    mahasiswaModel.nim = reader["nim"].ToString();
                    mahasiswaModel.nama = reader["nama"].ToString();
                    mahasiswaModel.rfid = reader["rfid"].ToString();
                    mahasiswaModel.pin = reader["pin"].ToString();
                    mahasiswaModel.jk = reader["jenis_kelamin"].ToString();
                    mahasiswaModel.jp = Convert.ToInt32(reader["jam_plus"]);
                    mahasiswaModel.jm = Convert.ToInt32(reader["jam_minus"]);
                    mahasiswaModel.softskil = reader["softskil"].ToString();
                    mahasiswaModel.status = reader["status"].ToString();
                }
                else
                {
                    return null;
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                throw;
            }
            finally
            {
                _connection.Close();
            }
            return mahasiswaModel;
        }

        public List<MahasiswaModel> getAllData()
        {
            List<MahasiswaModel> mahasiswaList = new List<MahasiswaModel>();
            try
            {
                string query = "SELECT * from mahasiswa";
                SqlCommand command = new SqlCommand(query, _connection);
                _connection.Open();
                SqlDataReader reader = command.ExecuteReader();
                while (reader.Read())
                {
                    MahasiswaModel mahasiswa= new MahasiswaModel
                    {
                        nim = reader["nim"].ToString(),
                        nama = reader["nama"].ToString(),
                        rfid = reader["rfid"].ToString(),
                        pin = reader["pin"].ToString(),
                        jk = reader["jenis_kelamin"].ToString(),
                        jp = Convert.ToInt32(reader["jam_plus"]),
                        jm = Convert.ToInt32(reader["jam_minus"]),
                        softskil = reader["softskil"].ToString(),
                        status = reader["status"].ToString(),
                    };
                    mahasiswaList.Add(mahasiswa);
                }
                reader.Close();
                _connection.Close();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
           

            return mahasiswaList;
        }

        public int GetTotalMahasiswa()
        {
            List<MahasiswaModel> mahasiswaList = getAllData();
            int totalMahasiswa = mahasiswaList.Count;
            return totalMahasiswa;
        }
        public MahasiswaModel getData(string id)
        {
            MahasiswaModel mahasiswaModel = new MahasiswaModel();
            try
            {
                string query = "select * from mahasiswa where nim = @p1";
                SqlCommand command = new SqlCommand(query, _connection);
                command.Parameters.AddWithValue("@p1", id);
                _connection.Open();
                SqlDataReader reader = command.ExecuteReader();
                reader.Read();
                mahasiswaModel.nim = reader["nim"].ToString();
                mahasiswaModel.nama = reader["nama"].ToString();
                mahasiswaModel.rfid = reader["rfid"].ToString();
                mahasiswaModel.pin = reader["pin"].ToString();
                mahasiswaModel.jk = reader["jenis_kelamin"].ToString();
                reader.Close();
                _connection.Close();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            return mahasiswaModel;
        }

        private string EncryptPIN(string pin)
        {
            using (SHA256 sha256Hash = SHA256.Create())
            {
                byte[] bytes = sha256Hash.ComputeHash(Encoding.UTF8.GetBytes(pin));

                StringBuilder builder = new StringBuilder();
                for (int i = 0; i < bytes.Length; i++)
                {
                    builder.Append(bytes[i].ToString("x2"));
                }
                return builder.ToString();
            }
        }

        public void insertData(MahasiswaModel mahasiswaModel)
        {
            try
            {
                string query = "insert into mahasiswa values(@p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9)";
                SqlCommand command = new SqlCommand(query, _connection);
                command.Parameters.AddWithValue("@p1", mahasiswaModel.nim);
                command.Parameters.AddWithValue("@p2", mahasiswaModel.nama);
                command.Parameters.AddWithValue("@p3", mahasiswaModel.rfid);
                string encryptedPassword = EncryptPIN(mahasiswaModel.pin);
                command.Parameters.AddWithValue("@p4", encryptedPassword);
                command.Parameters.AddWithValue("@p5", mahasiswaModel.jk);
                command.Parameters.AddWithValue("@p6", mahasiswaModel.jp);
                command.Parameters.AddWithValue("@p7", mahasiswaModel.jm);
                command.Parameters.AddWithValue("@p8", mahasiswaModel.softskil);
                command.Parameters.AddWithValue("@p9", mahasiswaModel.status);
                _connection.Open();
                command.ExecuteNonQuery();
                _connection.Close();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }

        public void updateData(MahasiswaModel mahasiswaModel)
        {
            try
            {
                string query = "update mahasiswa " +
                "set nama = @p2, " +
                "rfid = @p3, " +
                "pin = @p4, " +
                 "jenis_kelamin = @p5, " +
                "status = @p6 " +
                "where nim = @p1";

                using SqlCommand command = new SqlCommand(query, _connection);
                command.Parameters.AddWithValue("@p1", mahasiswaModel.nim);
                command.Parameters.AddWithValue("@p2", mahasiswaModel.nama);
                command.Parameters.AddWithValue("@p3", mahasiswaModel.rfid);
                
                string encryptedPassword = EncryptPIN(mahasiswaModel.pin);
                command.Parameters.AddWithValue("@p4", encryptedPassword);
                command.Parameters.AddWithValue("@p5", mahasiswaModel.jk);
               
                command.Parameters.AddWithValue("@p6", mahasiswaModel.status);
                _connection.Open();
                command.ExecuteNonQuery();
                _connection.Close();
            }
            catch (Exception ex)
            {
                Console.WriteLine("update : "+ex.Message);
            }
        }

        public void deleteData(string id)
        {
            try
            {
                string query = "DELETE FROM mahasiswa WHERE nim = @p1";
                using SqlCommand command = new SqlCommand(query, _connection);
                command.Parameters.AddWithValue("@p1", id);
                _connection.Open();
                command.ExecuteNonQuery();
                _connection.Close();
            }

PRG-4-PROJEK/Controllers/MahasiswaController.cs
using PRG_4_PROJEK.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace PRG_4_PROJEK.Controllers
{
    public class MahasiswaController : Controller
    {
        private readonly Mahasiswa _mahasiswaRepository;

        public MahasiswaController(IConfiguration configuration)
        {
            _mahasiswaRepository = new Mahasiswa(configuration);

        }

        public IActionResult Index()
        {

            MahasiswaModel mahasiswaModel = new MahasiswaModel();

            string serializedModel = HttpContext.Session.GetString("Identity");

            if (serializedModel == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                mahasiswaModel = JsonConvert.DeserializeObject<MahasiswaModel>(serializedModel);
            }

            return View(_mahasiswaRepository.getAllData());
        }

        [HttpGet]
        public IActionResult Create()
        {
            MahasiswaModel  mahasiswaModel = new MahasiswaModel();

            string serializedModel = HttpContext.Session.GetString("Identity");

            if (serializedModel == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                mahasiswaModel = JsonConvert.DeserializeObject<MahasiswaModel>(serializedModel);
            }
            return View();
        }

        [HttpPost]
        public IActionResult Create(MahasiswaModel mahasiswaModel)
        {
            if (_mahasiswaRepository.IsNIMAlreadyExists(mahasiswaModel.nim))
            {
                ModelState.AddModelError("NIM", "NIM sudah terdaftar.");
            }

            if (_mahasiswaRepository.IsRFIDAlreadyExists(mahasiswaModel.rfid))
            {
                ModelState.AddModelError("RFID", "RFID sudah terdaftar.");
            }

            if (ModelState.IsValid)
            {
                _mahasiswaRepository.insertData(mahasiswaModel);
                TempData["SuccessMessage"] = "Data berhasil ditambahkan";
                return RedirectToAction("Index");
            }

            return View(mahasiswaModel);
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            MahasiswaModel mahasiswaModel = new MahasiswaModel();


            MahasiswaModel MahasiswaModel = _mahasiswaRepository.getData(id);
            if (MahasiswaModel == null)
            {
                return NotFound();
            }
            return View(MahasiswaModel);
        }

        [HttpPost]
        public IActionResult Edit(MahasiswaModel mahasiswaModel)
        {
            Console.WriteLine("test : "+mahasiswaModel.ToString());

            if (ModelState.IsValid)
            {
                MahasiswaModel newMahasiswaModel = _mahasiswaRepository.getData(mahasiswaModel.nim);
                if (newMahasiswaModel == null)
                {
                    return NotFound();
                }

                newMahasiswaModel.nim  = mahasiswaModel.nim;
                newMahasiswaModel.nama = mahasiswaModel.nama;
                newMahasiswaModel.rfid = mahasiswaModel.rfid;
                
                newMahasiswaModel.pin = mahasiswaModel.pin;
                newMahasiswaModel.jk = mahasiswaModel.jk;
                newMahasiswaModel.status = mahasiswaModel.status;

                _mahasiswaRepository.updateData(newMahasiswaModel);
                TempData["SuccessMessage"] = "Mahasiswa berhasil diupdate.";
                return RedirectToAction("Index");
            }
            return View(mahasiswaModel);
        }

        [HttpPost]
        public IActionResult Delete(string id)
        {
            MahasiswaModel mahasiswaModel = new MahasiswaModel();

            var response = new { success = false, message = "Gagal menghapus data." };
            try
            {
                if (id != null)
                {
                    _mahasiswaRepository.deleteData(id);
                    response = new { success = true, message = "Berhasil menghapus data." };
                }
                else
                {
                    response = new { success = false, message = "Mahasiswa tidak ditemukan" };
                }
            }
            catch (Exception ex)
            {
                response = new { success = false, message = ex.Message };
            }
            return Json(response);
        }
    }
}

PRG-4-PROJEK/Views/Mahasiswa/Create.cshtml
@model PRG_4_PROJEK.Models.MahasiswaModel

@{
    ViewData["Title"] = "Tambah Mahasiswa";
}



<body>
  
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="pagetitle">
                    <h1>Mahasiswa</h1>
                    <nav>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">Mahasiswa</li>
                            <li class="breadcrumb-item active">Tambah Mahasiswa</li>
                        </ol>
                    </nav>
                </div>
                <form class="forms-sample" method="post">
                    <div class="form-group mb-3" >
                        <label asp-for="nim">NIM <span style="color: red;">*</span></label>
                        <input asp-for="nim" type="text" class="form-control input-with-border" placeholder="Nomor Induk Mahasiswa">
                        <span asp-validation-for="nim" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="nama">Nama <span style="color: red;">*</span></label>
                        <input asp-for="nama" type="text" class="form-control input-with-border" placeholder="Nama Mahasiswa">
                        <span asp-validation-for="nama" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="rfid">RFID <span style="color: red;">*</span></label>
                        <input asp-for="rfid" type="number" class="form-control input-with-border" placeholder="Nomor RFID">
                        <span asp-validation-for="rfid" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="pin">PIN <span style="color: red;">*</span></label>
                        <input asp-for="pin" type="number" class="form-control input-with-border" placeholder="Masukkan PIN">
                        <span asp-validation-for="pin" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="jk">Jenis Kelamin <span style="color: red;">*</span></label>
                        <select asp-for="jk" class="form-control input-with-border">
                            <option value="" disabled selected>Pilih Jenis kelamin</option>
                            <option value="laki-laki">Laki-laki</option>
                            <option value="perempuan">Perempuan</option>
                        </select>
                        <span asp-validation-for="jk" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <input asp-for="jp" type="text" class="form-control input-with-border" value="0" hidden >
                    </div>
                    <div class="form-group mb-3">
                        <input asp-for="jm" type="text" class="form-control input-with-border" value="0"hidden >
                    </div>
                    <div class="form-group mb-3">
                        <input asp-for="softskil" type="text" class="form-control input-with-border"value="0" hidden>
                    </div>
                    <div class="form-group mb-3">
                        <input asp-for="status" type="text" class="form-control input-with-border" placeholder="Status" value="aktif" hidden>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Simpan</button>
                            <a asp-controller="Mahasiswa" asp-action="Index" class="btn btn-light">Kembali</a>

                </form>
            </div>
        </div>
    </div>
</body>

PRG-4-PROJEK/Views/Mahasiswa/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model PRG_4_PROJEK.Models.MahasiswaModel
@{
    ViewData["Title"] = "Edit Mahasiswa";
}


<div class="content">
    <div class="contrainer-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                 
                    <div class="card-body">
                        <div class="pagetitle">
                            <nav>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item">Kegiatan</li>
                                    <li class="breadcrumb-item active">Edit Data Mahasiswa</li>
                                </ol>
                            </nav>
                        </div>
                        <form method="post" asp-controller="Mahasiswa" asp-action="Edit">
                            <div class="form-group mb-3">
                                <label asp-for="nim" class="control-label">NIM <span style="color: red;">*</span></label>
                                <input asp-for="nim" class="form-control" readonly />
                                <span asp-validation-for="nim" class="text-danger"></span>
                            </div>
                            <div class="form-group mb-3">
                                <label asp-for="nama" class="control-label">Nama Mahasiswa <span style="color: red;">*</span></label>
                                <input asp-for="nama" class="form-control" />
                                <span asp-validation-for="nama" class="text-danger"></span>
                            </div>
                            <div class="form-group mb-3">
                                <label asp-for="rfid" class="control-label">RFID <span style="color: red;">*</span></label>
                                <input asp-for="rfid" type="number" class="form-control" readonly />
                                <span asp-validation-for="rfid" class="text-danger"></span>
                            </div>
                            <div class="form-group mb-3">
                                <label asp-for="pin" class="control-label">Ubah PIN <span style="color: red;">*</span></label>
                                <input asp-for="pin" type="number" class="form-control" id="pin" />
                                <span asp-validation-for="pin" class="text-danger"></span>
                            </div>
                            <div class="form-group mb-3">
                                <label asp-for="jk">Jenis Kelamin <span style="color: red;">*</span></label>
                                <select asp-for="jk" class="form-control input-with-border">
                                    <option value="" disabled selected>Pilih Jenis kelamin</option>
                                    <option value="laki-laki">Laki-laki</option>
                                    <option value="perempuan">Perempuan</option>
                                </select>
                                <span asp-validation-for="jk" class="text-danger"></span>
                            </div>
@*                             <div class="form-group mb-3">
                                <input asp-for="jp" type="text" class="form-control input-with-border" value="jp" hidden>
                            </div>
                            <div class="form-group mb-3">
                                <input asp-for="jm" type="text" class="form-control input-with-border" value="jm" hidden>
                            </div>
                            <div class="form-group mb-3">
                                <input asp-for="softskil" type="text" class="form-control input-with-border" value="softskill" hidden>
                            </div> *@
                            <div class="form-group mb-3">
                                <input asp-for="status" type="text" class="form-control" placeholder="Status" value="aktif" hidden>
                            </div>
                            <div class="form-group mb-3">
                                <button type="submit" class="btn btn-primary">Simpan</button>
                                <a asp-controller="Mahasiswa" asp-action="Index" class="btn btn-danger">Batal</a>

                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PRG-4-PROJEK/Views/Mahasiswa/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<PRG_4_PROJEK.Models.MahasiswaModel>
@{
    ViewData["Title"] = "Mahasiswa";
    int no = 1;
}


<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Mahasiswa</h5>
                    <hr />
                    @if (TempData["SuccessMessage"] != null)
                    {
                        <div class="row">
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                <i class="bi bi-check-circle me-1"></i>
                                <strong>Sukses!</strong> @TempData["SuccessMessage"]
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        </div>
                    }
                    <a class="btn btn-primary" asp-action="Create">Tambah Mahasiswa</a>
                    <p></p>
                    <table class="table datatable" id="myTable">
                        <thead>
                            <tr>
                                <th scope="col">No</th>
                                <th scope="col">NIM</th>
                                <th scope="col">Nama</th>
                                <th scope="col">Jenis Kelamin</th>
                                <th scope="col">Jam Plus</th>
                                <th scope="col">Jam Minus</th>
                                <th scope="col">Aksi</th>
                            </tr>
                        </thead>
                       <tbody>
                            @foreach (var mahasiswa in Model)
                            {
                                <tr>
                                    <td>@(no++)</td>
                                    <td>@mahasiswa.nim</td>
                                    <td>@mahasiswa.nama</td>
                                    <td>@mahasiswa.jk</td>
                                    <td class="text-end">@mahasiswa.jp</td>
                                    <td class="text-end">@mahasiswa.jm</td>
                                    <td>

                                        <a asp-controller="Mahasiswa" asp-action="Edit" asp-route-id="@mahasiswa.nim" class="btn btn-sm btn-primary">
                                            <i class="fas fa-edit"></i>
                                        </a>

                                        <button class="btn btn-sm btn-danger delete-button" data-id="@mahasiswa.nim">
                                            <i class="fas fa-trash"></i>
                                        </button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js" integrity="sha512-GsLlZN/3F2ErC5ifS5QtgpiJtWd43JWSuIgh7mbzZ8zBps+dvLusV+eNQATqgA/HdeKFVgA5v3S/cIrLF7QnIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>
    $(document).ready(function () {
        $('#myTable').DataTable();
    });

    $(document).ready(function () {
        $(".delete-button").click(function () {
            var akunId = $(this).data("id");

            Swal.fire({
                title: "Hapus Mahasiswa?",
                text: "Apakah anda yakin ingin menghapus Mahasiswa ini?",
                icon: "warning",
                confirmButtonText: "Iya",
                showDenyButton: true,
                denyButtonText: "Tidak",
                dangerMode: true,
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        url: "/mahasiswa/Delete/" + akunId,
                        type: "POST",
                        success: function (data) {
                            if (data.success) {
                                Swal.fire("Sukses!", data.message, "success").then(() => {
                                    // Refresh halaman setelah pengguna menekan tombol "OK"
                                    location.reload();
                                });
                            } else {
                                Swal.fire("Gagal!", data.message, "error");
                            }
                        },
                        error: function () {
                            swal("Error", "Terjadi kesalahan saat menghapus Mahasiswa.", "error");
                        }
                    });
                }
            });
        });
    });
</script>