PRG-4-PROJEK/Controllers/AkunController.cs
using PRG_4_PROJEK.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace PRG_4_PROJEK.Controllers
{
    public class AkunController : Controller
    {
        private readonly Karyawan _karyawanRepository;

        public AkunController(IConfiguration configuration)
        {
            _karyawanRepository = new Karyawan(configuration);
        }

        public IActionResult Index()
        {
            KaryawanModel karyawanModel = new KaryawanModel();

            string serializedModel = HttpContext.Session.GetString("Identity");

            if (serializedModel == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                karyawanModel = JsonConvert.DeserializeObject<KaryawanModel>(serializedModel);
            }

            return View(_karyawanRepository.getAllData());
        }

        [HttpGet]
        public IActionResult Create()
        {
            KaryawanModel karyawanModel = new KaryawanModel();

            string serializedModel = HttpContext.Session.GetString("Identity");

            if (serializedModel == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                karyawanModel = JsonConvert.DeserializeObject<KaryawanModel>(serializedModel);
            }
            /*if (karyawanModel.jk == "admin")
            {
                return RedirectToAction("Index", "Pasien");
            }*/
            return View();
        }

        [HttpPost]
        public IActionResult Create(KaryawanModel karyawanModel)
        {

            if (_karyawanRepository.IsNPKAlreadyExists(karyawanModel.npk))
            {
                ModelState.AddModelError("NPK", "NPK sudah terdaftar.");
                return View("Create", karyawanModel); // Ganti dengan nama view Anda
            }

            if (ModelState.IsValid)
            {
                _karyawanRepository.insertData(karyawanModel);
                TempData["SuccessMessage"] = "Data berhasil ditambahkan";
                return RedirectToAction("Index");
            }
            return View(karyawanModel);
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            KaryawanModel karyawanModel = new KaryawanModel();
            KaryawanModel KaryawanModel = _karyawanRepository.getData(id);
            if (KaryawanModel == null)
            {
                return NotFound();
            }
            return View(KaryawanModel);
        }

        [HttpPost]
        public IActionResult Edit(KaryawanModel karyawanModel)
        {

            if (ModelState.IsValid)
            {
                KaryawanModel newAkunModel = _karyawanRepository.getData(karyawanModel.npk);
                if (newAkunModel == null)
                {
                    return NotFound();
                }

                newAkunModel.npk = karyawanModel.npk;
                newAkunModel.nama = karyawanModel.nama;
                newAkunModel.password = karyawanModel.password;
                newAkunModel.jk = karyawanModel.jk;
                newAkunModel.role = karyawanModel.role;
                newAkunModel.status = karyawanModel.status;

                _karyawanRepository.updateData(newAkunModel);
                TempData["SuccessMessage"] = "data berhasil diupdate.";
                return RedirectToAction("Index");
            }
            return View(karyawanModel);
        }


        [HttpPost]
        public IActionResult Delete(string id)
        {
            KaryawanModel karyawanModel = new KaryawanModel();

            var response = new { success = false, message = "Gagal menghapus data." };
            try
            {
                if (!string.IsNullOrEmpty(id) && int.TryParse(id, out int karyawanId))
                {
                    _karyawanRepository.deleteData(karyawanId);
                    response = new { success = true, message = "Berhasil menghapus data." };
                }
                else
                {
                    response = new { success = false, message = "Karyawan tidak ditemukan" };
                }
            }
            catch (Exception ex)
            {
                response = new { success = false, message = ex.Message };
            }
            return Json(response);
        }

    }
}

PRG-4-PROJEK/Controllers/DashboardController.cs
using PRG_4_PROJEK.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace PRG_4_PROJEK.Controllers
{
    public class DashboardController : Controller
    {
        private readonly Karyawan _karyawanRepository;
        private readonly Mahasiswa _mahasiswaRepository;
        private readonly Kegiatan _kegiatanRepository;
        private readonly Pengajuan _pengajuanRepository;

        public DashboardController(IConfiguration configuration)
        {
            _karyawanRepository = new Karyawan(configuration);
            _mahasiswaRepository = new Mahasiswa(configuration);
            _kegiatanRepository = new Kegiatan(configuration);
            _pengajuanRepository = new Pengajuan(configuration);
        }

        public IActionResult Index()
        {
            ViewBag.TotalKaryawan = _karyawanRepository.GetTotalKaryawan();
            ViewBag.TotalMahasiswa = _mahasiswaRepository.GetTotalMahasiswa();
            ViewBag.TotalKegiatan = _kegiatanRepository.GetTotalKegiatan();
            ViewBag.TotalPengajuan = _pengajuanRepository.GetTotalPengajuan();
            KaryawanModel karyawanModel = new KaryawanModel();

            string serializedModel = HttpContext.Session.GetString("Identity");

            if (serializedModel == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                karyawanModel = JsonConvert.DeserializeObject<KaryawanModel>(serializedModel);
            }

            return View(_karyawanRepository.getAllData());
        }

    }
}

PRG-4-PROJEK/Controllers/KegiatanController.cs
using PRG_4_PROJEK.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace PRG_4_PROJEK.Controllers
{
    public class KegiatanController : Controller
    {
        private readonly Kegiatan _kegiatanRepository;

        public KegiatanController(IConfiguration configuration)
        {


            _kegiatanRepository = new Kegiatan(configuration);
        }

        public IActionResult Index()
        {
            KegiatanModel kegiatanModel = new KegiatanModel();

            string serializedModel = HttpContext.Session.GetString("Identity");

            if (serializedModel == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                kegiatanModel = JsonConvert.DeserializeObject<KegiatanModel>(serializedModel);
            }

            return View(_kegiatanRepository.getAllData());
        }

        [HttpGet]
        public IActionResult Create()
        {
            KegiatanModel kegiatanModel = new KegiatanModel();

            string serializedModel = HttpContext.Session.GetString("Identity");

            if (serializedModel == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                kegiatanModel = JsonConvert.DeserializeObject<KegiatanModel>(serializedModel);
            }
            return View();
        }

        [HttpPost]
        public IActionResult Create(KegiatanModel kegiatanModel)
        {

            if (ModelState.IsValid)
            {
                _kegiatanRepository.insertData(kegiatanModel);
                TempData["SuccessMessage"] = "Data berhasil ditambahkan";
                return RedirectToAction("Index");
            }
            return View(kegiatanModel);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            KegiatanModel kegiatanModel = _kegiatanRepository.getData(id);

            if (kegiatanModel == null)
            {
                return NotFound();
            }

            return View(kegiatanModel);
        }



        [HttpPost]
        public IActionResult Edit(KegiatanModel kegiatanModel)
        {

            if (ModelState.IsValid)
            {
                KegiatanModel newKegiatanModel = _kegiatanRepository.getData(kegiatanModel.id_kegiatan);
                if (newKegiatanModel == null)
                {
                    return NotFound();
                }

                newKegiatanModel.id_kegiatan = kegiatanModel.id_kegiatan;
                newKegiatanModel.deskripsi = kegiatanModel.deskripsi;
                newKegiatanModel.kapasitas = kegiatanModel.kapasitas;
                newKegiatanModel.tglmulai = kegiatanModel.tglmulai;
                newKegiatanModel.tglselesai = kegiatanModel.tglselesai;
                newKegiatanModel.status = kegiatanModel.status;

                _kegiatanRepository.updateData(newKegiatanModel);
                TempData["SuccessMessage"] = "data berhasil diupdate.";
                return RedirectToAction("Index");
            }
            return View(kegiatanModel);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            // Membuat instance dari model KegiatanModel
            KegiatanModel kegiatanModel = new KegiatanModel();

        

            // Menghapus data berdasarkan ID
            var response = new { success = false, message = "Gagal menghapus data." };
            try
            {
                if (id != null)
                {
                    _kegiatanRepository.deleteData(id);
                    response = new { success = true, message = "Berhasil menghapus data." };
                }
                else
                {
                    response = new { success = false, message = "Kegiatan tidak ditemukan" };
                }
            }
            catch (Exception ex)
            {
                response = new { success = false, message = ex.Message };
            }

            // Langsung redirect ke dashboard tanpa memeriksa role
            return Json(response);
        }



    }
}

PRG-4-PROJEK/Controllers/LaporanController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PRG_4_PROJEK.Models;

namespace PRG_4_PROJEK.Controllers
{
    public class LaporanController : Controller
    {
        private readonly Mahasiswa _mahasiswaRepository;
        public LaporanController(IConfiguration configuration)
        {
            _mahasiswaRepository = new Mahasiswa(configuration);
        }
        public IActionResult Index()
        {
            MahasiswaModel mahasiswaModel = new MahasiswaModel();

            string serializedModel = HttpContext.Session.GetString("Identity");

            if (serializedModel == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                mahasiswaModel = JsonConvert.DeserializeObject<MahasiswaModel>(serializedModel);
            }

            return View(_mahasiswaRepository.getAllData());
        }

        [HttpGet]
        public ActionResult Detail(string id)
        {
            List<mhsLap> MahasiswaModel = _mahasiswaRepository.getDetail(id);
            Console.WriteLine("jumlah : "+MahasiswaModel.Count);
            Console.WriteLine("id : " + id);
            if (MahasiswaModel == null)
            {
                return NotFound();
            }
            return View(MahasiswaModel);
        }
    }
}

PRG-4-PROJEK/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PRG_4_PROJEK</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PRG_4_PROJEK.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PRG_4_PROJEK</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PRG_4_PROJEK - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PRG-4-PROJEK/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>@ViewData["Title"]</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/content/images/favicon.png" rel="icon">
    <link href="~/content/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/content/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/content/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/content/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/content/assets/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="~/content/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/content/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/content/assets/vendor/simple-datatables/style.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/content/assets/css/style.css" rel="stylesheet">

    <!-- =======================================================s
    * Template Name: NiceAdmin
    * Updated: Sep 18 2023 with Bootstrap v5.3.2
    * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <!-- Template Main JS File -->
    <script src="~/Content/assets/js/main.js"></script>
    <script src="https://cdn.jsdeLivr.net/npm/@@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://unpkg.com/sweetalert@2.1.2/dist/sweetalert.min.js"></script>

    <script src="https://cdn.datatables.net/plug-ins/1.10.25/i18n/Indonesian.json"></script>
<style>
.custom-h10 {
    font-size: 12px; /* Atur ukuran font sesuai keinginan Anda */
    font-weight: bold; /* Atur ketebalan font sesuai keinginan Anda */
}

    .custom-logout-btn {
        color: red !important;
    }
     .nav-link span {
        font-size: 18px; /* Adjust the font size as needed */
    }
     .header .logo span {
        font-size: 18px; /* Adjust the font size as needed */
    }

    .header .dropdown-toggle {
        font-size: 18px; /* Adjust the font size as needed */
    }
</style
</head>>


<body>

    <!-- ======= Header ======= -->
   <header id="header" class="header fixed-top d-flex align-items-center">
    @{
        var httpContext = ViewContext.HttpContext;
    }
    <div class="d-flex align-items-center justify-content-between">
        <a href="index.html" class="logo d-flex align-items-center">
            <img src="content/assets/img/logo.png" alt="">
            <span class="d-none d-lg-block">Monitoring</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->
    <li class="nav-item dropdown ms-auto">
        <a class="dropdown-toggle show-dropdown-arrow btn btn-inverse-primary btn-sm" id="profileDropdown" href="#" data-bs-toggle="dropdown">
            Hai, <strong>@httpContext.Session.GetString("Nama") (@httpContext.Session.GetString("Role"))</strong>
        </a>

        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
           <a class="dropdown-item" href="#" onclick="confirmLogout()">
                <i class="btn-icon bi bi-box-arrow-in-right"></i>
                Logout
            </a>
        </div>
    </li>
</header>
    <!-- ======= Sidebar ======= -->
        
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">
            @if (httpContext.Session.GetString("Role") == "admin")
            {
                <li class="nav-heading">Dashboard</li>
                <li class="nav-item">
                    <a class="nav-link collapsed" asp-controller="Dashboard" asp-action="Index">
                        <i class="bi bi-house-door-fill"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
                <li class="nav-heading">Transaksi</li>
                <li class="nav-item">
                    <a class="nav-link collapsed" asp-controller="DaftarKegiatan" asp-action="IndexP">
                        <i class="bi bi-box-arrow-up-right"></i>
                        <span>Pendaftaran</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link collapsed" asp-controller="DaftarKegiatan" asp-action="IndexJP">
                        <i class="bi bi-box-arrow-down"></i>
                        <span>Pengajuan</span>
                    </a>
                </li>
                <li class="nav-heading">Master</li>
                <li class="nav-item">
                    <a class="nav-link collapsed" asp-controller="Akun" asp-action="Index">
                        <i class="bi bi-person-bounding-box"></i>
                        <span>Karyawan</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link collapsed" asp-controller="Mahasiswa" asp-action="Index">
                        <i class="bi bi-people"></i>
                        <span>Mahasiswa</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link collapsed" asp-controller="Kegiatan" asp-action="Index">
                        <i class="bi bi-person-lines-fill"></i>
                        <span>Kegiatan</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link collapsed" asp-controller="Aktifitas" asp-action="Index">
                        <i class="bi bi-journal-text"></i>
                        <span>Aktivitas</span>
                    </a>
                </li>
               
            }
            @if (httpContext.Session.GetString("Role") == "sekprod")
            {
                <li class="nav-item">
                    <a class="nav-link collapsed" asp-controller="Dashboard" asp-action="Index">
                        <i class="bi bi-grid"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link collapsed" asp-controller="Laporan" asp-action="Index">
                        <i class="bi bi-patch-plus-fill"></i>
                        <span>Laporan </span>
                    </a>
                </li>
               
            }
            else
            {
                
            }
       
            
            
        </ul>
    </aside><!-- End Sidebar-->

    <main id="main" class="main">

   
        @RenderBody()

    </main><!-- End #main -->
    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
       
    </footer><!-- End Footer -->
     <script>
        function confirmLogout() {
            Swal.fire({
                title: 'Konfirmasi Logout',
                text: 'Apakah Anda yakin ingin logout?',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya, Logout!'
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = "@Url.Action("Logout", "Login")";
                }
            });
        }
        </script>

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="content/assets/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="content/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="content/assets/vendor/chart.js/chart.umd.js"></script>
    <script src="content/assets/vendor/echarts/echarts.min.js"></script>
    <script src="content/assets/vendor/quill/quill.min.js"></script>
    <script src="content/assets/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="content/assets/vendor/tinymce/tinymce.min.js"></script>
    <script src="content/assets/vendor/php-email-form/validate.js"></script>
     <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- Template Main JS File -->
    <script src="content/assets/js/main.js"></script>
     
</body>

</html>

PRG-4-PROJEK/Views/Shared/_LayoutMahasiswa.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>@ViewData["Title"]</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- base:css -->
    <link rel="stylesheet" href="~/content/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/content/vendors/base/vendor.bundle.base.css">
    <link rel="stylesheet" href="~/content/css/style.css">
    <link href="~/content/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/content/images/favicon.png" />


    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js" integrity="sha512-GsLlZN/3F2ErC5ifS5QtgpiJtWd43JWSuIgh7mbzZ8zBps+dvLusV+eNQATqgA/HdeKFVgA5v3S/cIrLF7QnIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="https://unpkg.com/sweetalert@2.1.2/dist/sweetalert.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.0/html2pdf.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.18.0/font/bootstrap-icons.css">



    <!--High CHart-->
    <script src="https://code.highcharts.com/highcharts.js"></script>

    <!-- Jika menggunakan CDN -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.css" />

    <style>
        .logo-container {
            padding-left: 30px;
        }
       
    </style>
</head>

<body style="background-color: #F7F7F9">
    <div class="horizontal-menu">
        <nav class="navbar top-navbar col-lg-12 col-12 p-0">
            <div class="container-fluid">
                <div class="navbar-menu-wrapper d-flex align-items-center justify-content-between">
                    <div class="logo-container">
                        <img src="~/content/images/IMG_Logo.png" alt="logo" style="max-width: 200px;" />
                    </div>
                    <ul class="navbar-nav navbar-nav-right">
                        @{
                            var httpContext = ViewContext.HttpContext;
                        }
                        <li class="nav-item dropdown d-lg-flex d-none">
                                <a asp-controller="DaftarKegiatan" asp-action="Index" class="nav-link collapsed">
                                    <span class="btn btn-inverse-primary btn-sm">Pengajuan</span>
                                </a>
                            </li>
                        <li class="nav-item dropdown ms-auto">
                            <a class="dropdown-toggle show-dropdown-arrow btn btn-inverse-primary btn-sm" id="profileDropdown" href="#" data-bs-toggle="dropdown">
                                Hai, <strong>@httpContext.Session.GetString("Nama")</strong>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                                <a class="dropdown-item" href="#" onclick="confirmLogout()">
                                    <i class="btn-icon bi bi-box-arrow-in-right"></i>
                                    Logout
                                </a>
                            </div>
                        </li>
                        <li class="nav-item dropdown d-lg-flex d-none">
                            <a asp-controller="DashboardMahasiswa" asp-action="Index" class="nav-link collapsed">
                                <span class="btn btn-inverse-primary btn-sm"><i class="fas fa-home"></i> Home</span>
                            </a>
                        </li>


                    </ul>
                    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
                            data-toggle="horizontal-menu-toggle">
                        <span class="mdi mdi-menu"></span>
                    </button>
                </div>
            </div>
        </nav>
    </div>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <main id="main" class="main">


        @RenderBody()

    </main><!-- End #main -->
   
    <!-- base:js -->
    <script>
        function confirmLogout() {
            Swal.fire({
                title: 'Konfirmasi Logout',
                text: 'Apakah Anda yakin ingin logout?',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya, Logout!'
            }).then((result) => {
                if (result.isConfirmed) {
                    // Redirect to the logout action
                    window.location.href = "@Url.Action("Logout", "LoginMahasiswa")";
                }
            });
        }
    </script>
    <script src="~/content/vendors/base/vendor.bundle.base.js"></script>

    <script src="~/content/js/template.js"></script>
    <script src="~/content/vendors/chart.js/Chart.min.js"></script>
    <script src="~/content/vendors/progressbar.js/progressbar.min.js"></script>
    <script src="~/content/vendors/chartjs-plugin-datalabels/chartjs-plugin-datalabels.js"></script>
    <script src="~/content/vendors/justgage/raphael-2.1.4.min.js"></script>
    <script src="~/content/vendors/justgage/justgage.js"></script>
    <script src="~/content/js/jquery.cookie.js" type="text/javascript"></script>
    <!-- Custom js for this page-->
    <script src="~/content/js/dashboard.js"></script>
    <!-- End custom js for this page-->

    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js" integrity="sha512-GsLlZN/3F2ErC5ifS5QtgpiJtWd43JWSuIgh7mbzZ8zBps+dvLusV+eNQATqgA/HdeKFVgA5v3S/cIrLF7QnIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</body>
</html>